modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="gstools"
version="1.0.0"
displayName="Ghost Spectora Tools"
displayURL="https://satosus.ddns.net"
logoFile="logo.png"
credits="https://www.youtube.com/@SatosusProject"
authors="The Satosus Project"
description="Global tools mod for all Satosus Project mods."

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.gstools]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.gstools]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration